name: Node CI

on: [push]


jobs:
  
  build:

    runs-on: ubuntu-latest
    env: 
      AWS_HOST: 3.110.188.180

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.2.11
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: 3.110.188.180
          REMOTE_USER: ec2-user
          TARGET: "~/backend/"
          EXCLUDE: "/dist/, /node_modules/"
          RUN: cd ~/backend && npm install
    - name: Run on Server
      run: |
            ssh -i ${{ secrets.SERVER_SSH_KEY }} ec2-user@{{AWS_HOST}}
            cd ~/backend 
            npm install

      # uses: easingthemes/ssh-deploy@main
      # env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      #     ARGS: "-rltgoDzvO --delete"
      #     SOURCE: "dist/"
      #     REMOTE_HOST: 3.110.188.180
      #     REMOTE_USER: ec2-user
      #     TARGET: "~/backend/"
      #     EXCLUDE: "/dist/, /node_modules/"
