name: CI deploy
on:
    push:
        branches: [development]
env:
    AWS_HOST: 15.207.71.4
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '14.17.0'

            - name: Build Server
              env:
                  CI: false
              run: |
                  echo "removing package.lock.json file"
                  echo "--------------------------------"
                  rm -rf package-lock.json
                  echo "Doing cache"
                  echo "--------------------------------"
                  npm cache clean --force
                  echo "Doing npm instaLL"
                  echo "--------------------------------"
                  npm install
                  echo "Conversion to JS file with 3GB memory size given to tsc compilor"
                  echo "--------------------------------"
                  NODE_OPTIONS=--max_old_space_size=3000 tsc -p .
                  echo "Printing file"
                  ls

    deploy:
      